### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [facebook/fbkutils#40]
I would like to point out that identifiers like “[`__LISTENER_H__`](https://github.com/facebook/fbkutils/blob/dc19f4b2ce7cfe3c2e8aabc13011013af25c6d45/netconsd/include/listener.h#L10 "Update candidate")” and “[`__OUTPUT_H__`](https://github.com/facebook/fbkutils/blob/dc19f4b2ce7cfe3c2e8aabc13011013af25c6d45/netconsd/include/output.h#L10 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by jcalvinowens** [comment]
> Would you like to adjust your selection for unique names?

If you can provide an example of a build environment that breaks because of the include guard naming, we'll happily merge a pull request to change it. Otherwise... it's one of those things that, while pedantically "wrong", doesn't really matter.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by jcalvinowens** [comment]
> How do you think about to avoid that this software depends on undefined behaviour?

Show me something this include guard naming actually breaks, and we'll happily merge a pull request to change it. I don't believe such a case exists. :)

**Comment by elfring** [comment]
I would find it nicer to [reduce the risk for undefined software behaviour](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") generally.
