### ISSUE TITLE
Checking if the key is in dictionary instead of using dict.get(key, -1)

### ISSUE THREAD

**Issue by farziengineer** [facebook/fbkutils#43]
https://github.com/facebook/fbkutils/blob/988bbdc252cd4c094be7a6e4241ca5f732db41fe/netesto/local/exp/exp.py#L191-L194

Some places in this file `fbkutils/netesto/local/exp/exp.py` has check if a key is in the dictionary and then tries to access it. It may be inefficient and less clean to go through the dictionary twice. Can I raise a PR to change these to

```python
 def getFieldIndex(s):
   return fieldDict.get(s, -1) 
```
@vmagro

**Comment by osandov** [comment]
Yes, that seems reasonable. Please open a PR.

**Comment by hmuhammadazeem** [comment]
@osandov Is it fixed or should I submit a PR?

**Comment by hmuhammadazeem** [comment]
@osandov May I submit a PR?
