### ISSUE TITLE
File explicitly closed can be replaced with"with open(file, 'r')" syntax

### ISSUE THREAD

**Issue by farziengineer** [facebook/fbkutils#44]
https://github.com/facebook/fbkutils/blob/988bbdc252cd4c094be7a6e4241ca5f732db41fe/netesto/local/processExp.py#L207-L216

The file `fbkutils/netesto/local/processExp.py` has the above code, which closes the file explictly. It can be replace by the following code. [Why use with open syntax](https://stackoverflow.com/questions/8009882/how-to-read-a-large-file-line-by-line-in-python)
```python 
with open(field_fn, 'r')  as fin:
   for iline in fin: 
     line = iline.strip() 
     if len(line) == 0: 
         continue 
     if line[0] != '#': 
         field = line.split(':') 
         fieldList.append(field[0]) 
         fieldOpDict[field[0]] = field[1] 
```

**Comment by osandov** [comment]
Please open a PR.
